util.plot.make_map: Add figsize argument
CLIMADA-project/climada_python pull request #165
Opened 2021-03-08 16:24 UTC by chahank

This addresses issue #135 and adds the keyword argument `figsize=(9, 13)` to `util.plot.make_plot` and to all the function/methods that call it too.

2021-03-15 08:39 UTC, tovogt approved these changes
Apart from some `optional` notes in the docstrings, this is fine from my side. If you feel generous, please replace all the docstrings you touched by NumPy style docstrings ;)

2021-03-15 08:39 UTC, tovogt commented on climada/entity/exposures/base.py
> +            figsize (tuple): figure size for plt.subplots
```suggestion
            figsize (tuple, optional): figure size for plt.subplots
```

2021-03-15 08:39 UTC, tovogt commented on climada/hazard/base.py
> +            figsize (tuple): figure size for plt.subplots
```suggestion
            figsize (tuple, optional): figure size for plt.subplots
```

2021-03-15 08:39 UTC, tovogt commented on climada/hazard/base.py
> +            figsize (tuple): figure size for plt.subplots
```suggestion
            figsize (tuple, optional): figure size for plt.subplots
```

2021-03-15 08:39 UTC, tovogt commented on climada/hazard/trop_cyclone.py
> +            figsize (tuple): figure size for plt.subplots
```suggestion
            figsize (tuple, optional): figure size for plt.subplots
```

2021-03-15 08:39 UTC, tovogt commented on climada/util/plot.py
> +        figsize (tuple): figure size for plt.subplots
```suggestion
        figsize (tuple, optional): figure size for plt.subplots
```

2021-03-15 08:39 UTC, tovogt commented on climada/util/plot.py
> +        figsize (tuple): figure size for plt.subplots
```suggestion
        figsize (tuple, optional): figure size for plt.subplots
```

2021-03-15 08:39 UTC, tovogt commented on climada/util/plot.py
> +        figsize (tuple): figure size for plt.subplots
```suggestion
        figsize (tuple, optional): figure size for plt.subplots
```

2021-03-18 13:57 UTC, emanuel-schmid requested changes

2021-03-18 13:57 UTC, emanuel-schmid commented on climada/entity/exposures/base.py
> +                                         axes=axis, figsize=fisgize, **kwargs)
```suggestion
                                         axes=axis, figsize=figsize, **kwargs)
```

2021-03-18 13:58 UTC, emanuel-schmid approved these changes

2021-03-18 13:59 UTC, merged