Feature/crop prod input
CLIMADA-project/climada_python pull request #246
Opened 2021-06-11 10:45 UTC by sameberenz

adding an alternative method (set_from_area_and_yield_nc4) to class CropProduction(Exposure) that allows expert users to initiate exposure of annual crop production [t/y] from two netcdf files containing yield [t/ha/y] and cultivated area [ha] information.

2021-06-14 08:34 UTC, carmensteinmann requested changes
Hi Sam!
Overall the code is easy to read, I don't have many comments. 
Regarding the structure: I would suggest splitting this function into two. 
1. an expert function that REQUIRES all your input variables
2. a wrapper calling on the first function for the dataset you're using. 

This would get rid of a lot of the if conditions. Moreover, I think the default values don't make much sense if they are used on an individual basis and we could expect an expert user to provide them. What do you think? 

Also, the second function could be simplified by having a variable called irr instead of yield_var and area_var, setting them both either to irr, noirr or combined.

2021-06-14 08:34 UTC, carmensteinmann commented on climada/entity/exposures/crop_production.py
> +            1: maize, 2: wheat, 3: rice(!), 4: soybean(!).
```suggestion
            1: maize, 2: wheat, 3: rice(!), 4: soybean(!).
            (!): layer number differs between default input files.
```

2021-06-15 09:51 UTC, sameberenz commented
Thanks for your suggestions @carmensteinmann. i have split the methods as you suggested. what do you think?

2021-06-15 11:37 UTC, carmensteinmann commented
@sameberenz I think it looks much clearer now, thanks a lot for adapting the code. 
I have one more note regarding variable names. I would suggest consistently using x_yield and x_area for all variables. Also, I think the names i_crop_yield and i_crop_area are quite unclear. 
My suggestions: 
- set_from_area_and_yield_nc4(self, crop_type, layer_yield, layer_area, filename_yield, filename_area, var_yield,                                    var_area, bbox=BBOX, input_dir=INPUT_DIR) and using data_area / data_yield within the function.
-layer_yield / layer_area instead of crop_idx_yield and crop_idx_area in set_from_spam_ray_mirca()

2021-06-15 14:49 UTC, sameberenz commented
Thanks for the suggestions @carmensteinmann , i have remaned the variables accordingly. What do you think?

2021-06-15 15:24 UTC, carmensteinmann commented on climada/entity/exposures/crop_production.py
> +        the parameters 'i_crop_*'.
```suggestion
        the parameters 'layer_*'.
```

2021-06-15 15:31 UTC, carmensteinmann approved these changes
For me it's ready to be merged.

2021-06-15 17:30 UTC, merged