Doc/update readme
CLIMADA-project/climada_python pull request #778
Opened 2023-08-30 15:09 UTC by chahank

Changes proposed in this PR:
- Small update of the readme including a clearer reference list.

This PR fixes #

### PR Author Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] Correct target branch selected (if unsure, select `develop`)
- [ ] Descriptive pull request title added
- [ ] Source branch up-to-date with target branch
- [ ] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#2.--Commenting-&-Documenting) updated
- [ ] [Tests][testing] updated
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]
- [ ] [Changelog](https://github.com/CLIMADA-project/climada_python/blob/main/CHANGELOG.md) updated

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Reviewer_Checklist.html) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/main/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html
[linter]: https://climada-python.readthedocs.io/en/stable/guide/Guide_Continuous_Integration_and_Testing.html#3.C.--Static-Code-Analysis

2023-08-31 06:27 UTC, peanutfun requested changes
I would like to keep the README as concise as possible. I suggest moving the most important articles to their own documentation page "How to Cite", where we can additionally provide a Bibtex file. I also find a lot of the formulations convoluted and not helpful. This is not due to this PR, but I suggest cleaning things up a bit as we are touching the README now 🙃

2023-08-31 06:27 UTC, peanutfun commented on README.md
> -Bresch, D. N. and Aznar-Siguan, G., 2021: CLIMADA v1.4.1: towards a globally consistent adaptation options appraisal tool, Geosci. Model Dev., 14, 351-363, https://doi.org/10.5194/gmd-14-351-2021
I suggest moving this into the documentation, maybe on its own page. I think this is too detailed information for a README. There, we can also provide, e.g., appropriate Bibtex entries

2023-08-31 06:27 UTC, peanutfun commented on README.md
>  Documentation is available on Read the Docs:
```suggestion
The online documentation is available on Read the Docs: https://climada-python.readthedocs.io/en/stable/

The documentation of each release version of CLIMADA can be accessed separately through the drop-down menu at the bottom of the left sidebar. Additionally, the version 'stable' refers to the most recent release (installed via `conda`), and 'latest' refers to the latest unstable development version (the `develop` branch).
```

2023-08-31 06:27 UTC, peanutfun commented on README.md
> +Note that all the documentations has two versions,'latest' and 'stable', and explicit version numbers, 'vx.x.x', in the url path. 'stable' is created from the latest release (installed via conda) and
```suggestion
```

2023-08-31 06:27 UTC, peanutfun commented on README.md
> +This is the Python (3.8+) version of CLIMADA - please see [https://github.com/davidnbresch/climada](https://github.com/davidnbresch/climada) for backward compatibility (MATLAB).
The link is already rendered as link? 🤔  Also, we're on Python 3.9 now
```suggestion
This is the Python (3.9+) version of CLIMADA - please see https://github.com/davidnbresch/climada for backward compatibility (MATLAB).
```

2023-08-31 06:27 UTC, peanutfun commented on README.md
> +As of today, CLIMADA provides global coverage of major climate-related extreme-weather hazards at high resolution via a [data API](https://climada.ethz.ch/data-api/v1/docs) such as tropical cyclones,
```suggestion
As of today, CLIMADA provides global coverage of major climate-related extreme-weather hazards at high resolution via a [data API](https://climada.ethz.ch/data-api/v1/docs) such as tropical cyclones, river flood, European winter storms, earthquakes, ..., all at 4km spatial resolution - wildfire to be added soon. For all hazards, historic and probabilistic event sets exist, for some also under select climate forcing scenarios (RCPs) at distinct time horizons (e.g. 2040).
You will find a repository containing scientific peer-reviewed articles that explain software components implemented in CLIMADA here: https://github.com/CLIMADA-project/climada_papers
```

2023-09-01 09:32 UTC, emanuel-schmid commented
In order to make the links work in the docs _and_ on the GitHub front page, we'll probably have to move both, CITATION_GUIDE.md and REFERENCES.bib to the root directory and symbolically link them within doc/misc.
Analogous to AUTHORS.md, CHANGELOG.md and CONTRIBUTING.md.

2023-09-01 13:27 UTC, chahank commented
@peanutfun : do you like the proposal so far?

2023-09-04 09:56 UTC, peanutfun requested changes
Content-wise, I agree. But I have a few technical points:
* Why are you using the `[link](link)` pattern? If you don't want to replace the link with text, you can just enter the link. It will be rendered as link automatically.
* There are a few instances where you use a "here" link, which is [highly discouraged](https://webmasters.stackexchange.com/questions/7114/how-to-avoid-click-here-links)
* To avoid the symlink-issue, I suggest making the citation guide an RST file which is only included in the documentation. The link in the README can then point to the appropriate readthedocs documentation page. I can do that.
* Currently, the citation guide document is not included in the Sphinx TOC tree and hence does not appear in the docs. I can fix that.

2023-09-04 12:01 UTC, chahank commented
> Content-wise, I agree. But I have a few technical points:
> 
>     * Why are you using the `[link](link)` pattern? If you don't want to replace the link with text, you can just enter the link. It will be rendered as link automatically.
No good reason then. I didn't know this always works. Thanks!
> 
>     * There are a few instances where you use a "here" link, which is [highly discouraged](https://webmasters.stackexchange.com/questions/7114/how-to-avoid-click-here-links)
While I do not fully agree with the strong opinion of this stack exchange, one can change it no problem.
> 
>     * To avoid the symlink-issue, I suggest making the citation guide an RST file which is only included in the documentation. The link in the README can then point to the appropriate readthedocs documentation page. I can do that.
May I ask what you mean by " is only included in the documentation."?
> 
>     * Currently, the citation guide document is not included in the Sphinx TOC tree and hence does not appear in the docs. I can fix that.
Cool thanks!

2023-09-04 13:17 UTC, chahank commented
I understand. Thanks for the explanation. Makes sense to me!

2023-09-05 09:24 UTC, peanutfun commented
> * To avoid the symlink-issue, I suggest making the citation guide an RST file which is only included in the documentation. The link in the README can then point to the appropriate readthedocs documentation page. I can do that.
> * Currently, the citation guide document is not included in the Sphinx TOC tree and hence does not appear in the docs. I can fix that.

I did both things and brushed up the citation guide a bit.

2023-09-11 09:10 UTC, emanuel-schmid commented
🙌 very nice.

2023-09-11 09:10 UTC, merged