Refine Risk Assessment Terms: Vulnerability and Impact Functions (Update Guide_Introduction.ipynb)
CLIMADA-project/climada_python pull request #802
Opened 2023-11-13 10:44 UTC by DahyannAraya

The choice of terminology in risk assessment models such as CLIMADA is crucial, as it shapes the framework and perspective of the analysis. The distinction between "vulnerability function" and "impact function" is particularly significant. I made some changes along the lines of making this terminology more visible. I also made changes in the documentation where vulnerability function or damage function was still referenced in order to unify the communication of CLIMADA terminology. 

I considered adding a few lines to explain that the concepts of damage function, vulnerability function, and impact function, though interrelated, each serve a distinct purpose. Damage functions quantify specific damages, focusing on concrete impacts. Vulnerability functions, in contrast, articulate the susceptibility of different exposures to hazards. This susceptibility encompasses more than just the potential for damage; it includes a variety of preconditions that define an exposure's overall vulnerability. Meanwhile, impact functions assess the likelihood of a hazard's effects, both negative and positive, by parameterizing the degree to which an exposure will be impacted by a particular hazard.Something along those lines..... but maybe it's too much... we can discuss it sometime ......

Changes proposed in this PR:
- 
- 

This PR fixes #

### PR Author Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] Correct target branch selected (if unsure, select `develop`)
- [ ] Descriptive pull request title added
- [ ] Source branch up-to-date with target branch
- [ ] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#2.--Commenting-&-Documenting) updated
- [ ] [Tests][testing] updated
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]
- [ ] [Changelog](https://github.com/CLIMADA-project/climada_python/blob/main/CHANGELOG.md) updated

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Reviewer_Checklist.html) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/main/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html
[linter]: https://climada-python.readthedocs.io/en/stable/guide/Guide_Continuous_Integration_and_Testing.html#3.C.--Static-Code-Analysis

2023-11-13 10:51 UTC, chahank commented
I think it is a great idea to clarify a bit the terminology. However, I think there are many more ways to interpret the words as those that you mentioned, so I would just be careful to not be to strong on the wording. The one thing we can be very clear about is what are `impact functions` in the context of CLIMADA. They are very flexible, and so can fulfill the roles of both `vulnerability functions` or `damage function`, but could also be `productivity functions` or `warning levels`. 

In any case, thanks for the updates!

2023-12-08 10:57 UTC, zeliest requested changes
I think it is good idea to clarify the terminology here. I would however not go more into detail as it is a general introduction, maybe in the tutorial on impact functions?

2023-12-08 10:57 UTC, zeliest commented on doc/guide/Guide_Introduction.ipynb
> +    "people, infrastructure and environment. In CLIMADA, vulnerability is\n",
I would leave out this sentence here as it is a bit of a repetition of what comes below: "In CLIMADA, vulnerability is operationalized through the use of impact functions, which are essential in determining the extent to which exposure is affected by a given hazard."

2023-12-08 10:57 UTC, zeliest commented on doc/guide/Guide_Introduction.ipynb
> +    "function' is broadly used in the modelers community, we adopt the term\n",
based on @chahank comment, I would modify the sentence "While the term 'vulnerability function' is broadly used in the modelers community, we adopt the term 'impact function' to explicitly include the option of opportunities (i.e. negative damages)" to something like "While the term 'vulnerability function' is broadly used in the modelers community, we adopt the broader term 'impact function'. Impact functions can be vulnerability functions or structural damage functions, but could also be productivity functions or warning levels. This definition also explicitly includes the option of opportunities (i.e. negative damages). "

2023-12-08 10:57 UTC, zeliest commented on doc/guide/Guide_Introduction.ipynb
> +    "(i.e. negative damages)**. Using this approach, CLIMADA constitutes a\n",
would make sense to have a new paragraph at "Using this approach..."

2024-04-09 07:31 UTC, chahank commented
@DahyannAraya : How is this PR going?

2024-04-30 14:28 UTC, DahyannAraya commented
OK @chahank, it's ready. I have implemented the changes suggested by @zeliest. You can do the merge, or if not, I'll wait for your confirmation and do it myself... Thanks

2024-04-30 14:50 UTC, chahank commented
Thanks @DahyannAraya ! But as you can see, all tests are failing. We need to fix this first. First thing to do is merge the `develop` branch into your branch as it has been a long time since this was done last. If tests are still failing, please try to fix them or seek help. 

@zeliest : can you please see if you are satisfied and approve the PR if yes (and if all tests are passing).

2024-05-02 14:39 UTC, merged