Create an empty centroids in Hazard.concat() with CRS from the first haz_list.
CLIMADA-project/climada_python pull request #881
Opened 2024-05-10 10:35 UTC by manniepmkam

Changes proposed in this PR:

This pull request is a fix for issue #879. 

An empty centroids is created in the `Hazard.concat()` function with the crs from the haz object from the haz_list.

This PR fixes #

### PR Author Checklist

- [x] Read the [Contribution Guide][contrib]
- [x] Correct target branch selected (if unsure, select `develop`)
- [x] Descriptive pull request title added
- [x] Source branch up-to-date with target branch
- [ ] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#2.--Commenting-&-Documenting) updated
- [ ] [Tests][testing] updated
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]
- [ ] [Changelog](https://github.com/CLIMADA-project/climada_python/blob/main/CHANGELOG.md) updated

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Reviewer_Checklist.html) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/main/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html
[linter]: https://climada-python.readthedocs.io/en/stable/guide/Guide_Continuous_Integration_and_Testing.html#3.C.--Static-Code-Analysis

2024-05-13 09:31 UTC, emanuel-schmid commented
Very well! Can you add tests and changelog?

2024-05-13 09:31 UTC, emanuel-schmid requested changes

2024-05-13 09:31 UTC, emanuel-schmid commented on climada/hazard/base.py
> +        haz_concat.centroids = Centroids(lat=[], lon=[], crs=haz_list[0].centroids.crs)
Exactly! 😄 
Alternatively one may inject the centroids as an argument of `haz_list[0].__class__`. (And possibly skip the `haz_type` assignment. I suspect that it is already assigned at that point through the constructor)

2024-05-31 15:17 UTC, peanutfun requested changes
@manniepmkam, as discussed in person, please
* fix the linter issue: Line too long
* add a unit test that covers the case reported in https://github.com/CLIMADA-project/climada_python/issues/879#issuecomment-2096281682

2024-06-17 13:19 UTC, manniepmkam commented
> @manniepmkam, as discussed in person, please
> 
> * fix the linter issue: Line too long
I have updated the line.

> * add a unit test that covers the case reported in [Issues with CRS when using  TropCyclone.from_tracks() #879 (comment)](https://github.com/CLIMADA-project/climada_python/issues/879#issuecomment-2096281682)
The unit test for hazard.base has been updated accordingly. Please review that.

2024-06-18 08:13 UTC, peanutfun requested changes
Looks good, but you should check for the exact error message and not just any `ValueError`, see my comment.

2024-06-18 08:13 UTC, peanutfun commented on climada/hazard/test/test_base.py
> +        with self.assertRaises(ValueError):
Please check the exact error that is raised using [`self.assertRaisesRegex`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaisesRegex), where the second argument is an expression that should appear in the error message. Notice that `haz5` does not define `units`, so the error might also originate from that.

2024-06-18 13:00 UTC, peanutfun approved these changes

2024-06-18 13:01 UTC, merged

2024-06-18 13:02 UTC, peanutfun commented
@manniepmkam Thanks a lot for the bugfix! 🙌