Restructuring of the documentation
CLIMADA-project/climada_python pull request #977
Opened 2024-11-15 07:45 UTC by spjuhel

This PR replaces PR #972 which was hastily merged and then reverted.
This PR fixes https://github.com/CLIMADA-project/climada_python/issues/969

Changes proposed in this PR:
- 
- 

This PR fixes #

### PR Author Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] Correct target branch selected (if unsure, select `develop`)
- [ ] Descriptive pull request title added
- [ ] Source branch up-to-date with target branch
- [ ] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#2.--Commenting-&-Documenting) updated
- [ ] [Tests][testing] updated
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]
- [ ] [Changelog](https://github.com/CLIMADA-project/climada_python/blob/develop/CHANGELOG.md) updated

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Review.html#reviewer-checklist) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/develop/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Testing.html
[linter]: https://climada-python.readthedocs.io/en/latest/guide/Guide_continuous_integration_GitHub_actions.html#static-code-analysis

2025-02-19 14:11 UTC, emanuel-schmid commented on doc/index.rst
> +CLIMADA (CLIMate ADAptation) is a free and open-source software framework for
Maybe add the link?

```suggestion
`CLIMADA <https://climada.ethz.ch>`_ (CLIMate ADAptation) is a free and open-source software framework for
```

2025-03-18 13:05 UTC, spjuhel commented
Ok! This is now almost ready for review!

I think I saw some tiny things that remain to be done in the index of Getting started index page, like an image to be  added (@NicolasColombi)

Otherwise, everything else is ready to be reviewed !

2025-03-19 08:15 UTC, NicolasColombi commented
> Ok! This is now almost ready for review!
> 
> I think I saw some tiny things that remain to be done in the index of Getting started index page, like an image to be added (@NicolasColombi)
> 
> Otherwise, everything else is ready to be reviewed !

Getting started is now finish an ready for review!

2025-04-07 09:52 UTC, chahank commented
General question: some of the tutorials "show" how to read and write files. So far, there was a folder named `results` in the tutorial folder where the written files were stored. Should we continue with this practice? Or shall we remove the file writing in the tutorial?

2025-05-14 14:25 UTC, ValentinGebhart commented
notice for book keeping: We might want to include a note that, if you want to review a branch that includes dependencies different to the ones of develop, you need to install (pip install) after checking out the branch. This is not explained in the installation instructions so far, and I was stuck not knowing what to do when I wanted to review such a branch.

2025-05-19 13:22 UTC, spjuhel commented
> notice for book keeping: We might want to include a note that, if you want to review a branch that includes dependencies different to the ones of develop, you need to install (pip install) after checking out the branch. This is not explained in the installation instructions so far, and I was stuck not knowing what to do when I wanted to review such a branch.

I have added the following to the reviewer guidelines (and a similar shorter comment in a few other places):

---

This is a generic set of instruction which should always work.

Assuming you already cloned the climada repository, and are at the root of that folder:

```
git fetch && git checkout <branch to review>
mamba create -n <choose a name>
mamba env update -n <same name> -f requirements/env_climada.yml
mamba activate <same name>
pip install -e ./
```

Creating a new python environment is strongly recommended, but not always necessary (*e.g.*, for minor feature branch that do not change the dependencies you can probably use a generic `develop` environment where you installed climada in editable mode)

2025-05-26 09:47 UTC, peanutfun requested changes
I really like the restructuring, but I found a few issues. Primarily, I think there are too many links in the top navbar, and the introduction header is a bit too much. Other than that, there are a few issues with links and the nesting structure.

2025-05-26 09:47 UTC, peanutfun commented on doc/index.rst
> +
```suggestion

**Useful links:** `WCR Group <https://wcr.ethz.ch/>`_ | `CLIMADA Petals <https://climada-petals.readthedocs.io/en/stable/>`_ | `CLIMADA website <https://climada.ethz.ch>`_ | `Mailing list <https://sympa.ethz.ch/sympa/info/climada-users>`_

```

2025-05-26 09:47 UTC, peanutfun commented on doc/development/dev-git.rst
> +   :hidden:
Do not hide it so the page itself shows the links and is not empty
```suggestion
```

2025-05-26 09:47 UTC, peanutfun commented on doc/getting-started/index.rst
> +Are you already working with mamba or conda? proceed to install CLIMADA by executing the following line in the terminal::
Maybe mention at least Mamba as a prerequisite?

2025-05-26 09:47 UTC, peanutfun commented on doc/development/index.rst
> +   Authors <../misc/AUTHORS>
Double title in the rendered document for some reason 🤔

2025-05-26 09:47 UTC, peanutfun commented on AUTHORS.md
> +(authors)=
Why necessary? This file is always referenced with its location, never with the link? (Right?)
```suggestion
```

2025-06-02 08:54 UTC, spjuhel commented on doc/development/dev-git.rst
> +   Guide_continuous_integration_GitHub_actions
Yeah, I wasn't sure about this. This confirms I should drop it :)

2025-06-02 08:56 UTC, spjuhel commented on doc/getting-started/index.rst
> +Are you already working with mamba or conda? proceed to install CLIMADA by executing the following line in the terminal::
Done

2025-06-02 09:31 UTC, spjuhel commented on doc/user-guide/index.rst
> +   Compute local exceedance <climada_util_local_exceedance_values>
Ok I struggled with this one, but I found the reason by comparing to Google Earth Engine tutorial:
The problem was that they were two "top-level" titles (with only one `#`) in the tutorial.
I'll add a short comment about that in the developer guide.

2025-06-02 09:52 UTC, spjuhel commented on doc/index.rst
>     Changelog <misc/CHANGELOG>
I had to change them to the actual "→" character to fix this. Found no better way.

@emanuel-schmid Is that fine?

2025-06-02 14:52 UTC, spjuhel commented
I don't know why the doc build fails now...

I merged develop, maybe a problem from that?

Otherwise I think it it ready to be merged

2025-06-04 13:32 UTC, peanutfun commented
@spjuhel seems like readthedocs had a hickup. I restarted the build and it succeeded!

2025-06-04 13:36 UTC, merged